### ISSUE TITLE
Leftover merge conflict

### ISSUE THREAD

**Issue by albertoastroc** [ChrisForti/devops-trifecta#8]
Hey Chris I was looking over the [create-vm.sh](https://github.com/ChrisForti/devops-trifecta/blob/main/create-vm.sh) file and on lines 88-93 it looks like there's leftover conflict markers.

```
# Copies webserver.sh to VM
<<<<<<< HEAD
scp -i ./id_ed25519 -o StrictHostKeyChecking=no webserver.sh aws-cli-install.sh jenkins-install.sh ansible-install.sh docker-install.sh amazon-cli-install.sh $USER@$(multipass info trifecta | grep IPv4 | awk '{ print $2 }'):~/
=======
scp -i ./id_ed25519 -o StrictHostKeyChecking=no jenkins-install.sh docker-install.sh $USER@$(multipass info trifecta | grep IPv4 | awk '{ print $2 }'):~/
>>>>>>> 39747409ea402465e6681c21b0981dbf4e963d63
```

Looks like the top line is the one that's meant to be kept since it has the other scripts included?

**Comment by ChrisForti** [comment]
Awesome thank you, I set this down, because I got alot going on.  I do need to start back with it, if you interested. I will send you a collaborator link. Thank you sir

**Comment by ChrisForti** [comment]
Yeah your right I copied  new file to my vm script. I remember a merge conflict, but don't think I ever investigated were it came from.
